<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Connection;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;
use RuntimeException;

/**
 * Tranche Booking pivot : référentiels service_type/status/channel
 * (+ processing_status pour FK nullable) + table booking partitionnée
 * (schema-booking-v1.sql). Extensions / charges hors périmètre.
 *
 * Écarts documentés vs schéma figé :
 * - id : GENERATED BY DEFAULT (au lieu de ALWAYS) — Doctrine ORM refuse
 *   IDENTITY sur PK composite ; pré-assignation nextval + INSERT explicite
 *   nécessitent BY DEFAULT. Sémantique IDENTITY + séquence globale inchangée.
 * - achat/vente_currency_code : DEFAULT 'TND' ajouté pour permettre
 *   l'INSERT ORM tant que la vague montants/devises ne mappe pas ces
 *   colonnes (schéma de référence : NOT NULL sans DEFAULT).
 * - pointvente_id / pointvente_paiement_id : BIGINT sans REFERENCES
 *   (module pointvente non importé).
 */
final class Version20260721220000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Import booking refs + pivot booking partitionné (slice schema-booking-v1.sql)';
    }

    public function isTransactional(): bool
    {
        return false;
    }

    public function up(Schema $schema): void
    {
        $sql = <<<'SQL'
CREATE TABLE booking_service_type (
    code        VARCHAR(30) PRIMARY KEY,
    sort_order  SMALLINT NOT NULL DEFAULT 0,
    is_active   BOOLEAN NOT NULL DEFAULT true,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO booking_service_type (code, sort_order) VALUES
    ('hotel',       0),
    ('flight',      1),
    ('transfer',    2),
    ('bus',         3),
    ('excursion',   4),
    ('car_rental',  5),
    ('spa',         6),
    ('pool_access', 7),
    ('visa',        8),
    ('maritime',    9),
    ('train',       10),
    ('guide',       11),
    ('other',       99);

CREATE TABLE booking_channel (
    code        VARCHAR(30) PRIMARY KEY,
    sort_order  SMALLINT NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO booking_channel (code, sort_order) VALUES
    ('backoffice', 0),
    ('web',        1),
    ('api_in',     2),
    ('api_out',    3);

CREATE TABLE booking_status (
    code                VARCHAR(30) PRIMARY KEY,
    service_type_code  VARCHAR(30) REFERENCES booking_service_type(code),
    is_final             BOOLEAN NOT NULL DEFAULT false,
    sort_order            SMALLINT NOT NULL DEFAULT 0,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO booking_status (code, service_type_code, is_final, sort_order) VALUES
    ('draft',       NULL, false, 0),
    ('on_option',   NULL, false, 1),
    ('confirmed',   NULL, false, 2),
    ('completed',   NULL, true,  3),
    ('cancelled',   NULL, true,  4),
    ('no_show',     NULL, true,  5);

CREATE TABLE booking_processing_status (
    code        VARCHAR(30) PRIMARY KEY,
    sort_order  SMALLINT NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO booking_processing_status (code, sort_order) VALUES
    ('pending_client_response',   0),
    ('client_contacted_serious',  1),
    ('pending_availability', 2);

CREATE TABLE booking (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    public_id                 UUID NOT NULL DEFAULT gen_random_uuid(),
    booking_date               DATE NOT NULL DEFAULT CURRENT_DATE,

    folder_id                   BIGINT NOT NULL REFERENCES booking_folder(id),
    service_type_code             VARCHAR(30) NOT NULL REFERENCES booking_service_type(code),
    status_code                     VARCHAR(30) NOT NULL REFERENCES booking_status(code),

    customer_account_id            BIGINT NOT NULL REFERENCES party_account(id),
    supplier_account_id              BIGINT REFERENCES party_account(id),
    office_account_id                  BIGINT NOT NULL REFERENCES party_account(id),

    start_date                           DATE NOT NULL,
    end_date                               DATE,

    -- DEFAULT 'TND' : écart slice vs schéma figé — voir docblock migration
    achat_currency_code                       VARCHAR(3) NOT NULL DEFAULT 'TND' REFERENCES ref_currency(code),
    achat_exchange_rate                         NUMERIC(14,6) NOT NULL DEFAULT 1,
    vente_currency_code                           VARCHAR(3) NOT NULL DEFAULT 'TND' REFERENCES ref_currency(code),
    vente_exchange_rate                             NUMERIC(14,6) NOT NULL DEFAULT 1,

    total_achat_amount                                BIGINT NOT NULL DEFAULT 0,
    total_vente_amount                                  BIGINT NOT NULL DEFAULT 0,
    marge_agence_amount                                   BIGINT NOT NULL DEFAULT 0,
    marge_distributeur_amount                               BIGINT NOT NULL DEFAULT 0,

    paid_amount                                               BIGINT NOT NULL DEFAULT 0,
    payment_status                                              VARCHAR(20) NOT NULL DEFAULT 'unpaid'
                                                                   CHECK (payment_status IN ('unpaid', 'partial', 'paid')),

    option_expiry_at                                              TIMESTAMPTZ,
    supplier_status_label                                            VARCHAR(100),
    is_on_request                                                      BOOLEAN NOT NULL DEFAULT false,
    price_breakdown                                                    JSONB NOT NULL DEFAULT '{}'::jsonb,
    channel_code                                                       VARCHAR(30) NOT NULL DEFAULT 'backoffice' REFERENCES booking_channel(code),

    assigned_agent_account_id                                          BIGINT REFERENCES party_account(id),
    assigned_at                                                        TIMESTAMPTZ,

    cancellation_fee_achat_amount                                      BIGINT NOT NULL DEFAULT 0,
    cancellation_fee_vente_amount                                      BIGINT NOT NULL DEFAULT 0,
    supplier_booking_reference                                         VARCHAR(100),
    origin_booking_id                                                    BIGINT,
    trip_type                                                              VARCHAR(20)
                                                                              CHECK (trip_type IN ('one_way', 'round_trip', 'multi_destination')),
    voucher_url                                                        VARCHAR(500),
    exclude_from_invoicing                                             BOOLEAN NOT NULL DEFAULT false,
    intended_payment_method                                            VARCHAR(20),
    contact_name                                                        VARCHAR(255),
    contact_phone                                                          VARCHAR(50),
    contact_email                                                             VARCHAR(255),
    contact_address                                                              VARCHAR(500),
    is_locked                                                                       BOOLEAN NOT NULL DEFAULT false,
    is_disputed                                                                        BOOLEAN NOT NULL DEFAULT false,
    processing_status_code                                                             VARCHAR(30) REFERENCES booking_processing_status(code),
    -- Sans REFERENCES pointvente : module non importé (écart slice)
    pointvente_id                                                                      BIGINT,
    pointvente_paiement_id                                                             BIGINT,

    created_at                                                           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                                                             TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by                                                               BIGINT REFERENCES party_account(id),
    updated_by                                                                 BIGINT REFERENCES party_account(id),

    CONSTRAINT ck_booking_dates CHECK (end_date IS NULL OR end_date >= start_date),

    PRIMARY KEY (id, booking_date)
) PARTITION BY RANGE (booking_date);

CREATE TABLE booking_y2026m07 PARTITION OF booking FOR VALUES FROM ('2026-07-01') TO ('2026-08-01');
CREATE TABLE booking_y2026m08 PARTITION OF booking FOR VALUES FROM ('2026-08-01') TO ('2026-09-01');
CREATE TABLE booking_y2026m09 PARTITION OF booking FOR VALUES FROM ('2026-09-01') TO ('2026-10-01');
CREATE TABLE booking_default   PARTITION OF booking DEFAULT;

CREATE UNIQUE INDEX uq_booking_public_id ON booking(public_id, booking_date);
CREATE INDEX idx_booking_folder ON booking(folder_id);
CREATE INDEX idx_booking_customer ON booking(customer_account_id);
CREATE INDEX idx_booking_supplier ON booking(supplier_account_id);
CREATE INDEX idx_booking_office ON booking(office_account_id);
CREATE INDEX idx_booking_status ON booking(status_code);
CREATE INDEX idx_booking_service_type ON booking(service_type_code);
CREATE INDEX idx_booking_start_date ON booking(start_date);
CREATE INDEX idx_booking_option_expiry ON booking(option_expiry_at) WHERE status_code = 'on_option';
CREATE INDEX idx_booking_on_request ON booking(id) WHERE is_on_request = true;
CREATE INDEX idx_booking_unassigned ON booking(booking_date) WHERE assigned_agent_account_id IS NULL;
CREATE INDEX idx_booking_supplier_reference ON booking(supplier_booking_reference) WHERE supplier_booking_reference IS NOT NULL;
CREATE INDEX idx_booking_origin ON booking(origin_booking_id) WHERE origin_booking_id IS NOT NULL;
CREATE INDEX idx_booking_disputed ON booking(id) WHERE is_disputed = true;
CREATE INDEX idx_booking_processing_status ON booking(processing_status_code) WHERE processing_status_code IS NOT NULL;
CREATE INDEX idx_booking_pointvente ON booking(pointvente_id) WHERE pointvente_id IS NOT NULL;
CREATE INDEX idx_booking_pointvente_paiement ON booking(pointvente_paiement_id) WHERE pointvente_paiement_id IS NOT NULL;

CREATE TRIGGER trg_booking_updated_at BEFORE UPDATE ON booking
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
SQL;

        $this->execSqlFile($this->connection, $sql);
    }

    public function down(Schema $schema): void
    {
        $this->throwIrreversibleMigrationException(
            'Les migrations SQL de référence ne sont pas réversibles automatiquement.'
        );
    }

    private function execSqlFile(Connection $connection, string $sql): void
    {
        $native = $connection->getNativeConnection();
        if (!$native instanceof \PDO) {
            throw new RuntimeException('Connexion PDO native attendue pour exécuter le SQL multi-statements.');
        }

        $native->exec($sql);
    }
}
