<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Ajuste booking.id en GENERATED BY DEFAULT pour autoriser l'INSERT
 * avec id pré-assigné (Doctrine composite PK + nextval).
 */
final class Version20260721220001 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'booking.id GENERATED BY DEFAULT (Doctrine composite PK + nextval)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE booking ALTER COLUMN id SET GENERATED BY DEFAULT');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE booking ALTER COLUMN id SET GENERATED ALWAYS');
    }
}
