-- ============================================================
-- Module : Core / Auth avancée (core_)
-- Réouverture ciblée de core_credential (provider -> table de
-- référence) + nouvelles tables session/MFA/tentatives.
-- ============================================================

-- ------------------------------------------------------------
-- Correction : provider en VARCHAR libre -> table de référence
-- (incohérence signalée en session, corrigée au passage puisque le
-- module est de toute façon rouvert pour Auth avancée).
-- ------------------------------------------------------------
CREATE TABLE core_credential_provider (
    code  VARCHAR(30) PRIMARY KEY
);

INSERT INTO core_credential_provider (code) VALUES
    ('local'), ('google'), ('facebook'), ('linkedin'), ('apple'), ('api_key'), ('sso_interne');

ALTER TABLE core_credential
    ADD CONSTRAINT fk_core_credential_provider FOREIGN KEY (provider) REFERENCES core_credential_provider(code);

-- ------------------------------------------------------------
-- Verrouillage par tentatives échouées + protection brute force par
-- compte (distinct du rate limiting IP, infra hors périmètre schéma).
-- ------------------------------------------------------------
ALTER TABLE core_credential
    ADD COLUMN failed_login_count SMALLINT NOT NULL DEFAULT 0,
    ADD COLUMN locked_until       TIMESTAMPTZ;

-- ============================================================
-- party_role_security_policy : politique de sécurité par party_role
-- (limite de sessions concurrentes, seuil de verrouillage) --
-- gouvernance interne uniquement, jamais délégable (cohérent avec le
-- plafond is_delegable côté RBAC).
-- ============================================================
CREATE TABLE party_role_security_policy (
    role_code                  VARCHAR(30) PRIMARY KEY REFERENCES party_role(code),
    max_concurrent_sessions    SMALLINT, -- NULL = illimité
    max_failed_login_attempts  SMALLINT NOT NULL DEFAULT 5,
    lockout_duration_minutes   SMALLINT NOT NULL DEFAULT 15,
    updated_at                 TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by                 BIGINT REFERENCES party_account(id)
);

INSERT INTO party_role_security_policy (role_code, max_concurrent_sessions) VALUES
    ('client', 2), ('internal_user', NULL), ('franchise', 3), ('fournisseur', NULL);

COMMENT ON TABLE party_role_security_policy IS 'Politique de sécurité par rôle structurel (party_role). Non délégable -- modifiable uniquement en interne (core.session_policy.manage, RBAC).';

-- ============================================================
-- core_session : trace de session/refresh token, PARTITIONNÉE par
-- date de création (cohérent avec booking_/log_ -- volume attendu
-- élevé). Rotation stricte : hash courant + hash précédent, jamais le
-- token en clair (même logique que password_hash).
-- ============================================================
CREATE TABLE core_session (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY, -- BY DEFAULT (pas ALWAYS) : PK composite (id, created_at) sur table partitionnée -- même contournement Doctrine que booking, amendement ADR-018 du 21/07/2026.
    account_id                  BIGINT NOT NULL REFERENCES party_account(id),
    current_refresh_token_hash  VARCHAR(255) NOT NULL,
    previous_refresh_token_hash VARCHAR(255),
    ip_address                  INET,
    user_agent_raw              TEXT, -- brut, parsing/géoloc recalculés à l'affichage (décision perf actée en session)
    is_revoked                  BOOLEAN NOT NULL DEFAULT false,
    revoked_reason              VARCHAR(30), -- 'logout','compromise_detected','admin_action', NULL si active
    last_used_at                TIMESTAMPTZ,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at                  TIMESTAMPTZ NOT NULL,

    PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);

CREATE TABLE core_session_y2026m07 PARTITION OF core_session
    FOR VALUES FROM ('2026-07-01') TO ('2026-08-01');
CREATE TABLE core_session_default PARTITION OF core_session DEFAULT;

CREATE INDEX idx_core_session_account_active ON core_session(account_id) WHERE is_revoked = false;
CREATE INDEX idx_core_session_current_hash ON core_session(current_refresh_token_hash) WHERE is_revoked = false;
-- Pas d'unicité en base : la colonne de partition (created_at) devrait figurer dans tout index unique,
-- ce qui rendrait la contrainte inopérante en pratique (deux insertions à quelques microsecondes
-- d'écart ne seraient jamais détectées comme doublon). Protection réelle = entropie du token généré
-- côté Application (128+ bits), pas une contrainte SQL. Trouvé par test de contrainte réelle en sandbox
-- le 20/07/2026, décision : accepté tel quel plutôt que complexifier avec une table de lookup séparée.

COMMENT ON TABLE core_session IS 'Sessions/refresh tokens, partitionnée par created_at (pg_partman à automatiser avant prod, même note que booking_). Rotation : previous_refresh_token_hash conservé une génération pour détecter la réutilisation (signal de compromission -> révocation de TOUTES les sessions actives du compte, décision actée en session).';

-- ============================================================
-- core_auth_attempt : tentatives d'authentification, réussies ET
-- échouées, PARTITIONNÉE, account_id nullable (email inexistant --
-- pas d'entité réelle à référencer). Table séparée de log_activity
-- pour isoler le bruit d'un brute force (décision perf/sécurité actée).
-- ============================================================
CREATE TABLE core_auth_attempt (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY, -- BY DEFAULT (pas ALWAYS) : PK composite (id, created_at) sur table partitionnée -- même contournement Doctrine que booking, amendement ADR-018 du 21/07/2026.
    identifier_attempted  VARCHAR(255) NOT NULL, -- email tapé, existe ou pas
    account_id            BIGINT REFERENCES party_account(id), -- NULL si compte inexistant
    success               BOOLEAN NOT NULL,
    failure_reason        VARCHAR(30), -- 'unknown_email','wrong_password','mfa_failed','account_locked', NULL si success
    ip_address             INET,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);

CREATE TABLE core_auth_attempt_y2026m07 PARTITION OF core_auth_attempt
    FOR VALUES FROM ('2026-07-01') TO ('2026-08-01');
CREATE TABLE core_auth_attempt_default PARTITION OF core_auth_attempt DEFAULT;

CREATE INDEX idx_core_auth_attempt_account ON core_auth_attempt(account_id, created_at) WHERE account_id IS NOT NULL;
CREATE INDEX idx_core_auth_attempt_identifier ON core_auth_attempt(identifier_attempted, created_at);

-- ============================================================
-- core_mfa_totp : secret TOTP par credential local. Chiffré côté
-- Application avant écriture (premier besoin de chiffrement applicatif
-- du projet -- vault/secret manager à trancher côté Backend, hors
-- périmètre schéma).
-- ============================================================
CREATE TABLE core_mfa_totp (
    credential_id     BIGINT PRIMARY KEY REFERENCES core_credential(id),
    secret_encrypted  VARCHAR(500) NOT NULL,
    is_enabled        BOOLEAN NOT NULL DEFAULT false,
    activated_at      TIMESTAMPTZ,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE core_mfa_totp IS 'Secret TOTP chiffré (jamais en clair) par credential local. Un seul secret actif par credential -- pas de rotation multi-device en V1 (non demandé).';

CREATE TABLE core_mfa_recovery_code (
    id             BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    credential_id  BIGINT NOT NULL REFERENCES core_credential(id),
    code_hash      VARCHAR(255) NOT NULL, -- haché, même logique que password_hash
    used_at        TIMESTAMPTZ, -- NULL = non consommé
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_core_mfa_recovery_code_credential ON core_mfa_recovery_code(credential_id) WHERE used_at IS NULL;

COMMENT ON TABLE core_mfa_recovery_code IS 'Lot de codes de récupération à usage unique, générés à l''activation du MFA, hachés. used_at marque la consommation (jamais de DELETE -- traçabilité).';

-- ============================================================
-- Garantie EN BASE : mfa_issuer_name (audit valeurs par défaut 24/07)
-- Dépend de config_application_setting (schema-permissions-config-v1.sql).
-- ============================================================

-- Trigger A : interdire d'ACTIVER le 2FA sans issuer renseigné
CREATE OR REPLACE FUNCTION core_mfa_require_issuer() RETURNS TRIGGER AS $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM config_application_setting
                   WHERE id = 1 AND btrim(coalesce(mfa_issuer_name,'')) <> '') THEN
        RAISE EXCEPTION 'Activation 2FA refusee : config_application_setting.mfa_issuer_name doit etre renseigne au prealable (nom affiche dans l''application d''authentification de l''utilisateur).'
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END; $$ LANGUAGE plpgsql;

CREATE TRIGGER trg_core_mfa_require_issuer
    BEFORE INSERT OR UPDATE OF is_enabled ON core_mfa_totp
    FOR EACH ROW WHEN (NEW.is_enabled)
    EXECUTE FUNCTION core_mfa_require_issuer();

-- Trigger B : interdire d'EFFACER l'issuer si des 2FA sont deja actifs
CREATE OR REPLACE FUNCTION config_protect_mfa_issuer() RETURNS TRIGGER AS $$
BEGIN
    IF btrim(coalesce(NEW.mfa_issuer_name,'')) = ''
       AND EXISTS (SELECT 1 FROM core_mfa_totp WHERE is_enabled) THEN
        RAISE EXCEPTION 'Effacement refuse : mfa_issuer_name ne peut pas etre vide tant que des utilisateurs ont le 2FA actif.'
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END; $$ LANGUAGE plpgsql;

CREATE TRIGGER trg_config_protect_mfa_issuer
    BEFORE UPDATE OF mfa_issuer_name ON config_application_setting
    FOR EACH ROW EXECUTE FUNCTION config_protect_mfa_issuer();
